### **Alex j Mathew **

QUES 1Create a vector, scalar, matrix and tensor with values
of your choice using tf.constant().




In [ ]:
# QUES 1
import tensorflow as tf


s = tf.constant(5)


v = tf.constant([1, 2, 3, 4, 5])


m=tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


tensor= tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


print("Scalar Tensor: ", s)
print("Vector Tensor: ", v)
print("Matrix Tensor: ", m)
print("3D Tensor: ", tensor)


Scalar Tensor:  tf.Tensor(5, shape=(), dtype=int32)
Vector Tensor:  tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Matrix Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
3D Tensor:  tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
import tensorflow as tf


s = tf.constant(5)


v = tf.constant([1, 2, 3, 4, 5])


m=tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


tensor= tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


print("Scalar Tensor: ", s)
print("Vector Tensor: ", v)
print("Matrix Tensor: ", m)
print("3D Tensor: ", tensor)


Scalar Tensor:  tf.Tensor(5, shape=(), dtype=int32)
Vector Tensor:  tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Matrix Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
3D Tensor:  tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


QUES 2 Find the shape, rank and size of the tensors (which you created for Q1).

In [ ]:
I = tf.shape(tensor)

In [ ]:
print(I)

tf.Tensor([2 2 2], shape=(3,), dtype=int32)


In [ ]:
H = tf.rank(tensor)
print(H)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
R = tf.size(tensor)
print(R)

tf.Tensor(8, shape=(), dtype=int32)


QUES 3 Create two tensors containing random values between 0 and 1 with
shape [5, 300]


In [ ]:
#QUESTION 3
tensor_1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor_2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float32)


print("Tensor 1: \n", tensor_1)
print("\nTensor 2: \n", tensor_2)

Tensor 1: 
 tf.Tensor(
[[0.26638186 0.28270602 0.6888238  ... 0.16998017 0.6884986  0.10926259]
 [0.7541386  0.612471   0.54233456 ... 0.21906137 0.82450485 0.4705565 ]
 [0.3820045  0.37195933 0.56536615 ... 0.82532465 0.94661474 0.6522052 ]
 [0.6007291  0.90065587 0.7932441  ... 0.58059657 0.47393143 0.5465802 ]
 [0.9819292  0.7856693  0.35116625 ... 0.417328   0.3448149  0.7870507 ]], shape=(5, 300), dtype=float32)

Tensor 2: 
 tf.Tensor(
[[0.6635498  0.4247818  0.50207484 ... 0.05945182 0.6485356  0.7591276 ]
 [0.9591149  0.57196105 0.33813584 ... 0.75283206 0.4195181  0.5201932 ]
 [0.00780439 0.6961956  0.4710952  ... 0.8399776  0.10442424 0.3403983 ]
 [0.01572311 0.7447064  0.89348996 ... 0.974445   0.74095094 0.78190863]
 [0.09189475 0.8967838  0.05941379 ... 0.50008464 0.41920233 0.25890398]], shape=(5, 300), dtype=float32)


QUES 4 Multiply the two tensors (which you created for Question 3) using matrix
multiplication


In [ ]:
result = tf.multiply(tensor_1, tensor_2)

In [ ]:
print(result)

tf.Tensor(
[[0.17675762 0.12008838 0.3458411  ... 0.01010563 0.44651586 0.08294424]
 [0.7233056  0.35030955 0.18338275 ... 0.16491643 0.34589472 0.2447803 ]
 [0.00298131 0.25895646 0.26634127 ... 0.69325423 0.09884952 0.22200955]
 [0.00944533 0.67072415 0.7087557  ... 0.5657594  0.35115993 0.42737576]
 [0.09023413 0.70457554 0.02086412 ... 0.20869932 0.14454721 0.20377056]], shape=(5, 300), dtype=float32)


QUES 5 Multiply the two tensors (which you created for Question 3) using dot product

In [ ]:
tensorA1 = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensorA2 = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
matrix_mult_result = tf.matmul(tensorA1, tensorA2)
print("1. Matrix multiplication result:\n", matrix_mult_result.numpy())

1. Matrix multiplication result:
 [[19. 22.]
 [43. 50.]]


 QUES 6 Create a tensor with random values between 0 and 1 with shape [224, 224,
3].


In [ ]:
import tensorflow as tf

tensoo = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1, dtype=tf.float32)

print(tensoro)

tf.Tensor(
[[[0.43727446 0.49724996 0.34230995]
  [0.7032044  0.44627082 0.23632753]
  [0.41069436 0.5518471  0.5311005 ]
  ...
  [0.2473135  0.9759344  0.8723117 ]
  [0.8761344  0.10454488 0.17329621]
  [0.69281197 0.23285842 0.40725684]]

 [[0.8949959  0.05824518 0.61982274]
  [0.18255258 0.93295276 0.37208474]
  [0.78520215 0.9482039  0.7944133 ]
  ...
  [0.88372886 0.19631183 0.58456194]
  [0.9073367  0.49973452 0.6136838 ]
  [0.5719776  0.665311   0.78745854]]

 [[0.52462685 0.8282449  0.33815598]
  [0.46460176 0.63227    0.26721454]
  [0.00146186 0.08775008 0.6289339 ]
  ...
  [0.37731278 0.7104194  0.68720055]
  [0.4345026  0.31099582 0.6285019 ]
  [0.93367136 0.2841879  0.60645616]]

 ...

 [[0.9245628  0.20932293 0.28510022]
  [0.97541153 0.9028233  0.8741263 ]
  [0.15312839 0.3311094  0.91470695]
  ...
  [0.619377   0.33646905 0.9895363 ]
  [0.87774944 0.6638411  0.04213166]
  [0.30935764 0.7791246  0.17360246]]

 [[0.337983   0.18774116 0.05735314]
  [0.563346   0.56882036 0

  QUES 7 find the min and max values of the tensors (Question 6)

In [ ]:
min_value = tf.reduce_min(tensor)
max_value = tf.reduce_max(tensor)
print(min_value)
print(max_value)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


QUES 8 Created a tensor with random values of shape [1, 224, 224, 3] then
squeeze it to change the shape to [224, 224, 3].


In [ ]:



tensor15 = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1, dtype=tf.float32)



squeezed_tensor = tf.squeeze(tensor15, axis=0)


print("Squeezed tensor shape", squeezed_tensor.shape)



Ques 9 Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
tensorH = tf.constant([1, 3, 5, 7, 9, 2, 4, 6, 8, 10], dtype=tf.float32)


print("Tensor:", tensor)


max_index = tf.argmax(tensor)


print("Index", max_index)

Tensor: tf.Tensor([ 1.  3.  5.  7.  9.  2.  4.  6.  8. 10.], shape=(10,), dtype=float32)
Index tf.Tensor(9, shape=(), dtype=int64)


 QUESTION 10 One-hot encode the tensor you created in 9

In [ ]:

tensorL = tf.constant([1, 3, 5, 7, 9, 2, 4, 6, 8, 10], dtype=tf.int32)


print("Tensor:", tensor)


max_index = tf.argmax(tensor)

print("Index of maximum value:", max_index.numpy())


depth = tf.reduce_max(tensor) + 1
one_hot_tensor = tf.one_hot(tensor, depth=depth)

print("One-hot encoded tensor:\n", one_hot_tensor.numpy())

Tensor: tf.Tensor([ 1  3  5  7  9  2  4  6  8 10], shape=(10,), dtype=int32)
Index of maximum value: 9
One-hot encoded tensor:
 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
